### ISSUE TITLE
System.out.println does not work

### ISSUE THREAD

**Issue by hrj** [jvilk/bfs-process#3]
Dependencies are a little over my head, so I might be wrong, but,

Should `bfs-process` declare a dependency on `events`? Because `process.ts` has:

```
import events = require('events');
```

---

I am actually trying to update doppio to use latest browserfs, and after updating to latest versions of browserfs, bfs-process, I was getting an error on that line in process.ts. Hence, I am just guessing that it is a missing dependency problem.

**Comment by jvilk** [comment]
Oh, interesting. It shouldn't, AFAIK; I believe `browserify` will bring it in as a builtin. Where/how are you getting that error? Also, Doppio is programmed to stub out some BrowserFS modules to prevent bundling BrowserFS into Doppio, but to allow referencing it like a module.

**Comment by jvilk** [comment]
Wait a minute... do you mean Doppio in a web browser? You should be able to just plop the newest version of BrowserFS onto a webpage, and use Doppio with it. Doppio picks it up via the global variable. (...at least, I think you can!)

**Comment by hrj** [comment]
Oh I see. Maybe something else goes wrong. I was trying the latest doppio + latest browserfs in the hopes of getting System.out.println() to work. But I hit different roadblocks (this was one of them), so I am backing up and sticking with the defaults for now.

Yes, this is in the browser environment.

I see that your jdk-jar branch in doppio has an updated dependency on browserfs. Though, that branch fails for some other reason. Here again, I will wait for you to merge the branch with master.

cheers!
